#!/usr/bin/env python3
"""
Test script for the enhanced text analysis system
Tests file upload capabilities and AI/plagiarism detection
"""

import sys
import os
sys.path.append('.')

from utils.text_analysis import TextAnalyzer
import io
import tempfile

def test_text_analyzer():
    """Test the TextAnalyzer functionality"""
    print("Testing Enhanced Text Analysis System")
    print("=" * 50)
    
    analyzer = TextAnalyzer()
    
    # Test 1: Basic text analysis
    print("\n1. Testing basic text analysis...")
    test_text = """
    This is a comprehensive test of our enhanced text analysis system. The artificial intelligence 
    detection algorithms will analyze patterns in writing style, vocabulary usage, and linguistic 
    characteristics to determine if content was generated by AI systems. Furthermore, the plagiarism 
    detection system will search for similarities with existing sources and provide detailed reports 
    about potential copied content. It is important to note that this analysis utilizes various 
    sophisticated techniques to ensure accurate detection of both AI-generated content and 
    plagiarized material.
    """
    
    result = analyzer.analyze_text(test_text, check_ai=True, check_plagiarism=True)
    
    if result.get('success'):
        print("✓ Text analysis successful")
        if 'ai_detection' in result:
            print(f"  AI Detection: {result['ai_detection']['score']}% ({result['ai_detection']['confidence']})")
        if 'plagiarism' in result:
            print(f"  Plagiarism: {result['plagiarism']['score']}% ({result['plagiarism']['confidence']})")
        print(f"  Explanation: {result['explanation']}")
    else:
        print(f"✗ Text analysis failed: {result.get('error')}")
        return False
    
    # Test 2: File format support
    print("\n2. Testing supported file formats...")
    formats = analyzer.get_supported_formats()
    print(f"✓ Supported formats: {', '.join(formats)}")
    
    # Test 3: Text file processing
    print("\n3. Testing text file processing...")
    test_content = "This is a test document for file upload analysis.\nIt contains multiple lines and should be processed correctly."
    
    # Create a temporary text file
    with tempfile.NamedTemporaryFile(mode='w', suffix='.txt', delete=False) as f:
        f.write(test_content)
        temp_file_path = f.name
    
    try:
        # Simulate file upload
        class MockFile:
            def __init__(self, content, filename):
                self.content = content.encode('utf-8')
                self.filename = filename
                self.position = 0
            
            def read(self):
                return self.content
            
            def seek(self, position, whence=0):
                if whence == 2:  # Seek from end
                    self.position = len(self.content) + position
                else:
                    self.position = position
            
            def tell(self):
                return self.position
        
        mock_file = MockFile(test_content, "test.txt")
        file_result = analyzer.extract_text_from_file(mock_file)
        
        if file_result['success']:
            print("✓ Text file processing successful")
            print(f"  Extracted {len(file_result['text'])} characters")
        else:
            print(f"✗ Text file processing failed: {file_result['error']}")
            
    finally:
        # Clean up
        if os.path.exists(temp_file_path):
            os.unlink(temp_file_path)
    
    # Test 4: Error handling
    print("\n4. Testing error handling...")
    
    # Test with empty text
    empty_result = analyzer.analyze_text("", check_ai=True, check_plagiarism=True)
    if not empty_result.get('success'):
        print("✓ Empty text properly rejected")
    else:
        print("✗ Empty text should be rejected")
    
    # Test with text too short
    short_result = analyzer.analyze_text("Short text", check_ai=True, check_plagiarism=True)
    if not short_result.get('success'):
        print("✓ Short text properly rejected")
    else:
        print("✗ Short text should be rejected")
    
    print("\n" + "=" * 50)
    print("Enhanced Text Analysis System Test Complete")
    return True

if __name__ == "__main__":
    success = test_text_analyzer()
    if success:
        print("✓ All tests passed - System ready for production")
        sys.exit(0)
    else:
        print("✗ Some tests failed - Please check the system")
        sys.exit(1)