#!/usr/bin/env python3
"""
Simple test to verify the unified text analysis system is working.
This tests the shared service and route logic.
"""

import sys
sys.path.append('.')

from services.text_analysis import analyze_text_content

def test_unified_system():
    """Test that the shared text analysis service provides consistent results"""
    print("Testing Unified Text Analysis System")
    print("=" * 40)
    
    # Test text
    test_text = """
    This is a comprehensive test of our unified text analysis system. The artificial intelligence 
    detection algorithms analyze writing patterns, vocabulary usage, and sentence structure to 
    determine if content was generated by AI. Similarly, the plagiarism detection system checks 
    for matches against known sources and web content to identify copied material.
    """
    
    print(f"Test text length: {len(test_text)} characters")
    print(f"Text preview: {test_text[:100]}...")
    
    # Test different source types to ensure consistency
    sources_to_test = ['homepage', 'manual', 'file_upload']
    results = {}
    
    for source in sources_to_test:
        print(f"\nTesting source: {source}")
        result = analyze_text_content(
            test_text.strip(), 
            check_ai=True, 
            check_plagiarism=True, 
            source=source
        )
        
        if result.get('success'):
            ai_score = result.get('ai_detection', {}).get('percentage', 0)
            plag_score = result.get('plagiarism', {}).get('percentage', 0)
            print(f"  ✓ AI Detection: {ai_score}%")
            print(f"  ✓ Plagiarism: {plag_score}%")
            results[source] = {'ai': ai_score, 'plagiarism': plag_score}
        else:
            print(f"  ✗ Failed: {result.get('error')}")
            return False
    
    # Check consistency across sources
    print(f"\n{'-' * 40}")
    print("CONSISTENCY CHECK")
    print(f"{'-' * 40}")
    
    first_source = sources_to_test[0]
    first_result = results[first_source]
    
    all_consistent = True
    for source in sources_to_test[1:]:
        current_result = results[source]
        
        if (current_result['ai'] == first_result['ai'] and 
            current_result['plagiarism'] == first_result['plagiarism']):
            print(f"✓ {source} matches {first_source}")
        else:
            print(f"✗ {source} differs from {first_source}")
            print(f"  {source}: AI={current_result['ai']}%, Plag={current_result['plagiarism']}%")
            print(f"  {first_source}: AI={first_result['ai']}%, Plag={first_result['plagiarism']}%")
            all_consistent = False
    
    print(f"\n{'-' * 40}")
    print("RESULTS SUMMARY")
    print(f"{'-' * 40}")
    
    if all_consistent:
        print("✓ SUCCESS: All sources provide identical results!")
        print("✓ Homepage message analysis uses same logic as Text Authenticity Analysis")
        print("✓ Shared service working correctly")
        print("✓ No duplicate implementations")
        
        # Show final scores
        print(f"\nFinal Analysis Results:")
        print(f"  AI Detection: {first_result['ai']}% likelihood of AI-generated content")
        print(f"  Plagiarism: {first_result['plagiarism']}% similarity to existing sources")
        
        return True
    else:
        print("✗ FAILURE: Inconsistent results found")
        return False

if __name__ == "__main__":
    success = test_unified_system()
    if success:
        print("\n🎉 Unified text analysis system is working perfectly!")
        sys.exit(0)
    else:
        print("\n❌ Issues found with unified system")
        sys.exit(1)